id: PA2C9269C
initial_creation_type: input
source_metadata:
  title: Rinchen Terdzö Series
  language: fr
  description: 'Texts belonging to (and related to) the Rinchen Terdzö (rin chen gter
    mdzod) or Precious Treasury of Revelations, one of the five treasuries of Jamgön
    Kongtrul Lodrö Thayé (1813–1899). Note that the volume numbers below correspond
    to the Shechen Publications edition (2007–2008):'
  volume:
    e226578cbd2c4afd8c1616aa1f430677:
      title: 'A Garland of Vajra Gems: The Life and Liberation of the Guru'
      parent: Volume 1
    fcea96d216eb43fb9835015aa516b206:
      title: The Life and Liberation of Padmākara, the Second Buddha from A Precious
        Garland of Lapis Lazuli
      parent: Volume 1
    222e397b0af446f2a68b28c2bc60c0a6:
      title: 'The Melodious Sound of Gathering Auspiciousness: A Prayer Based on the
        Liberational Life of the Omniscient Jamyang Khyentse Wangpo'
      parent: Volume 1
    4593f386daae47d2a49efec854dda92a:
      title: 'The Melodious Speech of Samantabhadra: A Prayer to the Glorious Master
        Jamgön Kongtrul Thaye'
      parent: Volume 1
    b32b6b07a6614b63b6cc9beb45b70095:
      title: 'A Beautiful and Wondrous Udumbara Garland: A Supplication and Summary
        of the Chronicles of Padma, The Life and Liberation of the Precious Guru of
        Uḍḍiyāna'
      parent: Volume 1
    b83ee677dc934f89b15e8588257297b1:
      title: A Prayer Recalling the Life and Liberation of the Precious Master Padmasambhava
      parent: Volume 1
    8b40f598efaa45fa84b8d32ed029c38a:
      title: 'Cloud Banks of Blessings: A Prayer Recounting the Eleven Deeds of the
        Life and Liberation of the Guru from Uḍḍiyāna'
      parent: Volume 1
    8b3ff712b18548c388e95aa233b0fa1e:
      title: 'Three Reasons for Confidence: A Work Telling the Life and Liberation
        Story of the Great Master Padmākara'
      parent: Volume 1
    31b326b178c44a90a74fd79f07f27a46:
      title: The Lament of Rudra
      parent: Volume 5
    90c33fe525114cb9b2090c4bf24df9fb:
      title: 'Le''u Dünma—Chapter 1: The Prayer to the Three Kāya Guru'
      parent: Volume 5
    79ef0b0c45094de88b7c2dbc4ad1eb83:
      title: 'Le''u Dünma—Chapter 2: The Prayer Requested by King Tri Songdetsen'
      parent: Volume 5
    aba76b20f08147c28ee82775b2687414:
      title: 'Le''u Dünma—Chapter 3: The Prayer Requested by Khandro Yeshe Tsogyal'
      parent: Volume 5
    1adb36d3fb1f42609ec669264efbe8fa:
      title: 'Le''u Dünma—Chapter 4: The Prayer Requested by Namkhe Nyingpo'
      parent: Volume 5
    6fcee872c405462dbc88f36de1fe7e00:
      title: 'Le''u Dünma—Chapter 5: The Prayer Requested by Nanam Dorje Dudjom'
      parent: Volume 5
    126063a9d8bf4866bee1a8a062b91e62:
      title: 'Le''u Dünma—Chapter 6: The Prayer Requested by Prince Mutri Tsenpo'
      parent: Volume 5
    48ee5150146f4c8e8ebe10aff1bc5cf6:
      title: Le'u Dünma—Chapter 7. The Prayer to Guru Rinpoche that Spontaneously
        Fulfills All Wishes (Sampa Lhundrupma)
      parent: Volume 5
    a876fa732b42433bbba1e37c080a4ed4:
      title: 'The Brilliant Essence: The Ritual Manual for the Secret Embodiment of
        the Guru (Lama Sangdü)'
      parent: Volume 6
    9acc9367ad6e4242a3893f787379305a:
      title: The Prayer Which Removes All Obstacles from the Path (Barché Lamsel)
      parent: Volume 10
    00f6c753d2de45888f37f496fdcf6e21:
      title: 'The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma) from The Guru’s Heart Practice: The Wish-Fulfilling Jewel'
      parent: Volume 10
    405cebe60bd1417d9eee19bfe2fe5837:
      title: 'The Vajra Lute: A Brief Fulfilment for the Guru Practice of Vidyādhara-Assembly'
      parent: Volume 10
    ba2f611199504eab8e40084c8d2468f1:
      title: 'A Glimpse of the Crucial Points: The Vidyādhara''s Manual of Concealed
        Instructions'
      parent: Volume 10
    42fe62dad6284d149da971745686dc53:
      title: The Root Empowerment of the Vase Conferring Majesty from the Heart-Essence
        of the Vast Expanse
      parent: Volume 10
    265cf5c3a9cf428bae9fb5aa39ade741:
      title: The Spontaneous Vajra Song of Fulfilment and Confession
      parent: Volume 10
    22ca0dee07c34771bb1554a91b66fdd6:
      title: The Vidyādhara Assembly (Rigdzin Düpa), the Inner Practice from the Heart
        Essence of the Vast Expanse
      parent: Volume 10
    e2a27a6b3d7245ec8789a0eebf1ab864:
      title: The Prayer of the Tenth Days in Guru Rinpoche’s Life Story entitled ‘The
        Nucleus of Blessings’
      parent: Volume 11
    248d4c4af5e243a8ad47dfc86fea92d8:
      title: 'The Tambura’s Yearning Song of Devotion: A Prayer Summarizing Khandro
        Yeshe Tsogyal’s Life and Liberation'
      parent: Volume 11
    ecdd4a8bbadd43cfb96b9f68f66052fa:
      title: 'The Offering Clouds of the Indestructible Ladies of Sound: Concise Garland
        of Offerings of the Sixteen Vajra Goddesses'
      parent: Volume 11
    00b7532b2ce747b996743a0495088882:
      title: The Invocation of Uḍḍiyāna on the Tenth Day
      parent: Volume 11
    b8069d7a7b8344539846a53dd7d47592:
      title: Ārya Mañjuśrī Tantra Garbha
      parent: Volume 16
    47f2e53af805416d9e5c9a0fad8a5936:
      title: Ārya Mañjuśrī Tantra Garbha—commentary
      parent: Volume 16
    418d41a75b4a4cb1867b80f5791ac04d:
      title: Dedication from Vajravārāhī Cycle of Namchö revealed by Mingyur Dorje
      parent: Volume 21
    214aa167f6494afea9c3dacc1991e538:
      title: 'The Wish-Fulfilling Jewel: A Daily Sādhana of the Noble Avalokiteśvara'
      parent: Volume 22
    2d657905d150433a9c53eb15446ae2c2:
      title: Prayer to the Lineage of the Supreme Hayagrīva Emanation from the Aural
        Transmission
      parent: Volume 26
    727f24609f59470489f9876324464746:
      title: 'Meeting the Buddha Face to Face: A Pith Instruction on Realizing the
        Fortress, Ravine, and View of the Practice of Vajrakīla'
      parent: Volume 31
    47c1d4ad90d940d1bccb6e9fe0d54043:
      title: The History of the Hearing Lineage of the Profound and Secret Practice
        of Siṃhamukhā
      parent: Volume 32
    f7e26a972f9a4f96bd846169195e301a:
      title: 'The Cascading Essence of Great Bliss: An Empowerment Ritual for the
        Female Practice of the Queen of Great Bliss, from the Heart Essence of the
        Vast Expanse'
      parent: Volume 36
    167a9fe24d344e70bb64f9b1b878affa:
      title: 'The Fount of Longevity: The Chimé Pakmé Nyingtik Lineage Prayer'
      parent: Volume 36
    bae9a3964f30446487c3f7aaa876179b:
      title: Activities for Uncovering Primordial Wisdom from the Chimé Pakmé Nyingtik,
        ‘The Heart Essence of the Sublime Lady of Immortality’
      parent: Volume 36
    bc6a8ba766404990a7b49dd0a210735e:
      title: 'The Garland of Utpala Flowers: A Prayer to the Masters of the Lineage
        of Zabtik Drolchok'
      parent: Volume 36
    6ea4ec8c7292460d8b0edfffdbcaab43:
      title: 'The Shower of Great Bliss: A Prayer to the Lineage of the Female Awareness-Holder
        (Yumka)'
      parent: Volume 36
    96d133cce8194d51ac314b15ead150d7:
      title: The Single-Form Daily Practice from Chimé Pakmé Nyingtik (The Heart Essence
        of the Sublime Lady of Immortality)
      parent: Volume 36
    c509f86c169b49b8b5056972d29b1c95:
      title: A Glorious Garland of Great Bliss, the Root Sādhana of the Queen of Great
        Bliss, Yumka Tsogyal, from the Heart Essence of the Vast Expanse
      parent: Volume 36
    88f408d444294d5d929551774806ed5c:
      title: The Twenty-Eight Commitments
      parent: Volume 41
    911bd35af85b4b58826ef4cb4893c835:
      title: The Ultimate Inexpressible Confession (Yeshe Kuchokma)
      parent: Volume 41
    1e3bf486a0d444939b34d4f752fa3561:
      title: Verses of Confession 'Düsum Deshekma'
      parent: Volume 41
    d83ff7cb8e3846dd97ab804f81b8370c:
      title: 'Emptying the Hells from their Very Depths: The Sovereign Practice for
        the Confession of all Impairments and Breakages of Vows and all Negative Actions
        and Obscurations'
      parent: Volume 41
    a6a2bf630eff42a2be212880224a631d:
      title: Offering the Eight Auspicious Substances and Seven Emblems of Royalty
      parent: Volume 41
    4ba94269d74b42d1a0d361d637e8a668:
      title: 'The Rain of Virtue and Goodness: A Short Practice for Consecrating Representations
        of Enlightened Body, Speech and Mind'
      parent: Volume 41
    8071f803937c4350b7b2fb4b10e6e843:
      title: 'Damchen Chitor: A Brief Practice of Torma Offering to the Oath-Bound
        Guardians'
      parent: Volume 41
    f222769848e24d90ab38184a64631118:
      title: 'Jewels of Many Colours: Ordinary Fire Pūjas for the Four Activities
        Based on a Single Substance to Easily Conclude Approach and Accomplishment'
      parent: Volume 42
    e619c8e19e68412ba2b9c2c0a52225b5:
      title: 'Liberation Upon Hearing: An Explanation of the Phenomena of the Intermediate
        State'
      parent: Volume 42
    89b8f9518d6e4ee18a8abdcd0c4469b9:
      title: 'Bright Light of the Sun: A Simple Fire Offering Based on a Single Substance'
      parent: Volume 42
    584678469c1d40c3b64346b19673d929:
      title: White and Red Sur Offerings That Are Very Easy to Apply
      parent: Volume 43
    d856eab35a1c47eea8d70912afb666cd:
      title: The Mountain Smoke Offering (Riwo Sangchö)
      parent: Volume 43
    cd8fb434df164b70bbc4c5567005e3e3:
      title: The Means for Accomplishment called the Blazing Wheel
      parent: Volume 45
    55c26a72edff422280a1151f6c816a87:
      title: Dispeller of All Samaya Corruptions and Pollutions
      parent: Volume 47
    6fb0ddd6f33343e1a7d906d34168cbef:
      title: 'The New Glorious Bestower of Immortality: A Long-Life Practice and Empowerment
        that Unites the Oral, Treasure and Visionary Teachings'
      parent: Volume 48
    4307cf59ad2d4b7cb2c164d04875465d:
      title: The Sādhana and Empowerment for the Extremely Close Lineage of the Long-Life
        Practice that Unites the Oral, Treasure and Visionary Teachings
      parent: Volume 48
    6f88f73f12424c21a0359bfa8521f23e:
      title: The Dhāraṇīs That Encapsulate the Essence of the Kangyur, the Collected
        Words of the Buddha
      parent: Volume 48
    b72dd62e2e95478d877bbd72d176ea55:
      title: 'Opening the Door to Great Bliss: An Aspiration Towards the Realm of
        Abhirati'
      parent: Volume 48
    e97715ef65514e53bdf073ee4b4bff0a:
      title: 'The Essence of Benefit and Happiness: A Method for Saving Lives'
      parent: Volume 49
    81642bcd2a734a6594592f55bd172616:
      title: The Indestructible Vajra Garland, An Aspiration Prayer for the Lives
        of the Supreme Holders of the Non-Sectarian Teachings
      parent: Volume 49
    7740a922f45a476a8f5cae50ae3d7123:
      title: 'The Bestowal of Supreme Immortality: A Prayer to the Lineage of Mitrayogin’s
        White and Red Amitāyus'
      parent: Volume 49
    e140adc94844441599afb275cf09e26f:
      title: Prayer for the Future of the Dharma
      parent: Volume 52
    7430dc644284436ca3b904b75c3d9770:
      title: A Practice of Paying Homage and Making Offerings to the Sixteen Elders
      parent: Volume 52
    d368c23737a54778b42bd336469e3475:
      title: A Prayer to Jowo Rinpoche Combined with Aspirations and a Means to Receive
        the Four Empowerments
      parent: Volume 52
    006d2e00ce92440bbadd6458f9af336c:
      title: 'The Treasury of Blessings: A Practice of Buddha Śākyamuni'
      parent: Volume 52
    4d0d37c5427f4d858f8366a160edeb87:
      title: The Aspiration of the Vajradhātu Maṇḍala
      parent: Volume 60
    2f58cfc11ad54f83ad7b681e280b05ff:
      title: 'Words to Delight the Sovereigns of the Dharma: A Prayer of Aspiration
        for the Flourishing and Spread of the Ancient Translation Tradition'
      parent: Volume 60
    73ff1fc0ca8f42938b49095ed40f555a:
      title: The Pointing-the-Staff Instruction
      parent: Volume 60
    cd6ef1a8daeb4349ae28f231a3045d00:
      title: Yeshe Tsogyal's Prayer
      parent: Volume 60
    bfa16e163fe84346be73a88c636b2a6b:
      title: The Powerful Prayer of Aspiration from the Tantra of the Great Perfection
        that Reveals the All-Penetrating Wisdom Mind of Samantabhadra (Kunzang Mönlam)
      parent: Volume 60
    235a0c794a0147b589c67e717db9e396:
      title: 'Radiant Sunlight of the Victors’ Teachings: A Brief, First-Hand Account
        of the Liberating Life-Story of the Great Emanated Treasure Revealer'
      parent: Volume 65
    46d668495126473b95e810eb4ddceff9:
      title: The Brief Tsok Feast Offering Prayer from 'The Profound Path of the Ḍākinīs'
        Heart Drop'
      parent: Volume 67
created_at: '2022-03-01T05:31:39.695426'
last_modified_at: '2022-03-01T05:31:39.695429'
